module Sprue
  autoload(:Agent, 'sprue/agent')
  autoload(:Backlog, 'sprue/backlog')
  autoload(:Client, 'sprue/client')
  autoload(:Connection, 'sprue/connection')
  autoload(:Context, 'sprue/context')
  autoload(:Dispatcher, 'sprue/dispatcher')
  autoload(:Entity, 'sprue/entity')
  autoload(:Job, 'sprue/job')
  autoload(:Queue, 'sprue/queue')
  autoload(:Repository, 'sprue/repository')
  autoload(:Serializer, 'sprue/serializer')
  autoload(:SortedArray, 'sprue/sorted_array')
  autoload(:Worker, 'sprue/worker')
end
